---
version: '2'
services:

  db:
    image: 'ticketator/db'
    build: ./docker/db
    env_file: './docker/envs/${DOCKER_COMPOSE_ENV}.env'

  backend:
    image: 'ticketator/backend'
    build: .
    env_file: './docker/envs/${DOCKER_COMPOSE_ENV}.env'
    volumes:
      - .:/code
      - /tmp/ticketator:/static
    ports:
      - '8000:8000'
    depends_on:
      - db
