---
version: '3'
services:

  db:
    image: 'ticketator/db'
    build: ./docker/db
    env_file: './docker/envs/${DOCKER_COMPOSE_ENV}.env'
    volumes:
      - /tmp/docker/ticketator/postgresql/data/:/var/lib/postgresql/data
      - /tmp/docker/ticketator/postgresql/log/:/var/log/postgresql

  backend:
    image: 'ticketator/backend'
    build: .
    env_file: './docker/envs/${DOCKER_COMPOSE_ENV}.env'
    volumes:
      - .:/code
      - /tmp/ticketator:/static
    ports:
      - '8000:8000'
    depends_on:
      - db
