version: '2'

services:
  database:
    image: sameersbn/postgresql:9.5-1
    build: db/
    env_file: envs/${DOCKER_COMPOSE_ENV}.env
    volumes:
       - /srv/docker/ticketator/postgresql/data/:/var/lib/postgresql/data

  backend:
    image: ticketator/backend
    build: backend/
    env_file: envs/${DOCKER_COMPOSE_ENV}.env
    volumes:
      - .:/code
      - /tmp/ticketator:/static
    ports:
      - '8000:8000'
    depends_on:
      - database

volumes:
  ticketator-db-volume:
    external: true
