version: '2'

services:

  db:
    image: sameersbn/postgresql:9.5-1
    build: ./docker/db
    env_file: './docker/envs/${DOCKER_COMPOSE_ENV}.env'
    volumes:
       - ticketator-db-volume:/var/lib/postgresql:Z

  backend:
    image: 'ticketator/backend'
    build: .
    env_file: './docker/envs/${DOCKER_COMPOSE_ENV}.env'
    volumes:
      - .:/code
      - /tmp/ticketator:/static
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  ticketator-db-volume:
    external: true
